// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PensionManagementPortal.DatabaseRepo;

namespace PensionManagementPortal.Migrations.DbHelperMigrations
{
    [DbContext(typeof(DbHelper))]
    [Migration("20210819201309_local_data_2")]
    partial class local_data_2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("PensionManagementPortal.Models.PensionData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<double>("AadharNumber")
                        .HasColumnType("float");

                    b.Property<double>("BankCharges")
                        .HasColumnType("float");

                    b.Property<DateTime>("DateOFWithdraw")
                        .HasColumnType("datetime2");

                    b.Property<double>("PensionAmount")
                        .HasColumnType("float");

                    b.HasKey("Id", "AadharNumber");

                    b.ToTable("pension");
                });

            modelBuilder.Entity("PensionManagementPortal.Models.PensionInput", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<double>("AadharNumber")
                        .HasColumnType("float");

                    b.Property<string>("BankAccountType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PanNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id", "AadharNumber");

                    b.ToTable("userDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
